
headers_load_des = [
                "Numero de control",
                "Fecha de solicitud",
                "Numero Cotizacion",
                "PT",
                "Producto",
                "Cliente",
                "Notificacion Sanitaria",
                "Estado Muestra",
                "Diseno Desarrollo",
                "Numero de Fragancia",
                "NIT",
                "Comercial",
                "Marca",
                "Check"         
            ]
campos_load_des = [
            "Numero de control",
            "Fecha de solicitud (yyyy-mm-dd)",
            "Numero Cotizacion",
            "PT",
            "Producto",
            "Cliente",
            "Notificacion Sanitaria",
            "Estado Muestra",
            "Diseno Desarrollo",
            "Numero de Fragancia",
            "NIT",
            "Comercial",
            "Marca"
        ]
headers_load_cos = [
                "Numero Control",
                "Fecha Solicitud",
                "Numero Cotizacion",
                "PT",
                "Producto",
                "Codigo Envase No Decorado",
                "Descripcion Envase No Decorado",
                "Suministra Envase",
                "Color Envase",
                "Material Envase",
                "Capacidad Envase",
                "Codigo Tapa No Decorado",
                "Descripcion Tapa No Decorado",
                "Suministra Tapa",
                "Color Tapa",
                "Material Tapa",
                "Codigo Foil",
                "Foil",
                "Tipo Foil",
                "Codigo Banda",
                "Banda",
                "Ubicacion Banda",
                "Codigo Etiqueta",
                "Etiqueta",
                "Codigo Plegadiza",
                "Caja Plegadiza",
                "Suministra Caja",
                "Diseno Bodega",
                "Tipo de Envase",
                "Cuello Envase",
                "Sellado Envase",
                "Tipo Tapa",
                "Tipo Valvula",
                "Sobre Tapa",
                "Estilo Tapa",
                "Acabado Casquete",
                "Color Casquete",
                "Envase Decorado",
                "Codigo Envase Decorado",
                "Descripcion Envase Decorado",
                "Tapa Decorada",
                "Codigo Tapa Decorada",
                "Descripcion Tapa Decorada",
                "Etiqueta Tapa Decorada",
                "Codigo Etiqueta Tapa Decorada",
                "Lleva Foil",
                "Lleva Termoencogible",
                "Lleva Escurridor",
                "Codigo Escurridor",
                "Descripcion Escurridor",
                "Lleva Capilar",
                "Observaciones Capilar",
                "Dimensiones Capilar",
                "Lleva Accesorios",
                "Descripcion Accesorio",
                "Check"
            ]
campos_update_cost = [
                "Codigo Envase No Decorado", "Descripcion Envase No Decorado", "Suministra Envase", "Color Envase", "Material Envase", "Capacidad Envase",
                "Codigo Tapa No Decorado", "Descripcion Tapa No Decorado", "Suministra Tapa", "Color Tapa", "Material Tapa",
                "Codigo Foil", "Foil", "Tipo Foil",
                "Codigo Banda", "Banda", "Ubicacion Banda",
                "Codigo Etiqueta", "Etiqueta",
                "Codigo Plegadiza", "Caja Plegadiza", "Suministra Caja",
                "Diseno Bodega", "Tipo de Envase", "Cuello Envase", "Sellado Envase",
                "Tipo Tapa",
                "Tipo Valvula",
                "Sobre Tapa",
                "Estilo Tapa",
                "Acabado Casquete",
                "Color Casquete",
                "Envase Decorado",
                "Codigo Envase Decorado",
                "Descripcion Envase Decorado",
                "Tapa Decorada",
                "Codigo Tapa Decorada",
                "Descripcion Tapa Decorada",
                "Etiqueta Tapa Decorada",
                "Codigo Etiqueta Tapa Decorada",
                "Lleva Foil",
                "Lleva Termoencogible",
                "Lleva Escurridor",
                "Codigo Escurridor",
                "Descripcion Escurridor",
                "Lleva Capilar",
                "Observaciones Capilar",
                "Dimensiones Capilar",
                "Lleva Accesorios",
                "Descripcion Accesorio"
            ]
desplegables_cost = {
                "Lleva Capilar": ["SI", "NO"],
                "Lleva Accesorios": ["SI", "NO"],
                "Lleva Foil": ["SI", "NO"],
                "Diseno Bodega": ["SI", "NO"],
                "Lleva Escurridor": ["SI", "NO"],
                "Lleva Termoencogible": ["SI", "NO"],
                "Material Envase": ["PET", "PEAD","ALUMINIO"],
                "Suministra Envase": ["CLIENTE", "CLIENTE INT","GB LAB"],
                "Suministra Tapa": ["CLIENTE", "CLIENTE INT","GB LAB"],
                "Material Tapa": ["PET", "PEAD","ALUMINIO"],
                "Sobre Tapa": ["SI","NO"],
                "Estilo Tapa": ["LISA","ESTRIADA"],
                "Acabado Casquete": ["NEGRO","BLANCO","DORADO","PLATEADO"],
                "Color Casquete": ["BRILLANTE","MATE"],
                "Tipo Foil": ["ESPUMADO", "DE TORQUE","DE CALOR","DE CARTON"],
                "Tipo Tapa": ["ROSCA", "SIN ROSCA","CON APLICADOR","FLIP TOP DISCO OVALO","FLIP TOP DISCO REDONDO","GOTERO","PUSH PULL","VALVULA"],
                "Cuello Envase": ["18/410", "18/415","20/410","20/415","24/410","24/415","28/410","28/415"],
                "Tipo Valvula": ["AGRETE-FERULA", "SPRAY","TRATAMIENTO","ESPUMERA","AIRLESS","TRIGGER","MINI TRIGGER","CREMERA CIERRE LATERAL","CREMERA CIERRE ROSCA"],
                "Tipo Envase": ["FRASCO (*CUELLO)", "ENVASE (*CUELLO)","ENVASE AIRLESS","POTE PLASTICO","POTE DE VIDRIO","ENVASE PSEUDOCOLAPSIBLE","TUBO COLAPSIBLE","DOYPACK","SACHET"]
            }
ordered_campos_cost = [
                        "Codigo Envase No Decorado", "Descripcion Envase No Decorado", "Suministra Envase", "Color Envase", "Material Envase", "Capacidad Envase",
                        "Codigo Tapa No Decorado", "Descripcion Tapa No Decorado", "Suministra Tapa", "Color Tapa", "Material Tapa",
                        "Codigo Foil", "Foil", "Tipo Foil",
                        "Codigo Banda", "Banda", "Ubicacion Banda",
                        "Codigo Etiqueta", "Etiqueta",
                        "Codigo Plegadiza", "Caja Plegadiza", "Suministra Caja",
                        "Diseno Bodega", "Tipo de Envase",
                        "Cuello Envase",
                        "Sellado Envase",
                        "Tipo Tapa",
                        "Tipo Valvula",
                        "Sobre Tapa",
                        "Estilo Tapa",
                        "Acabado Casquete",
                        "Color Casquete",
                        "Envase Decorado",
                        "Codigo Envase Decorado",
                        "Descripcion Envase Decorado",
                        "Tapa Decorada",
                        "Codigo Tapa Decorada",
                        "Descripcion Tapa Decorada",
                        "Etiqueta Tapa Decorada",
                        "Codigo Etiqueta Tapa Decorada",
                        "Lleva Foil",
                        "Lleva Termoencogible",
                        "Lleva Escurridor",
                        "Codigo Escurridor",
                        "Descripcion Escurridor",
                        "Lleva Capilar",
                        "Observaciones Capilar",
                        "Dimensiones Capilar",
                        "Lleva Accesorios",
                        "Descripcion Accesorio"
                    ]
headers_load_cal = [
                    "Numero Control",
                    "Fecha Solicitud",
                    "Numero Cotizacion",
                    "PT",
                    "Producto",
                    "Mesofilos",
                    "E Coli",
                    "S Aureus",
                    "P Aureoginosa",
                    "Moho y Levaduras",
                    "Observaciones Microbiologia",
                    "Cumple Microbiologia",
                    "Densidad",
                    "Ph",
                    "Contenido",
                    "Color",
                    "Textura",
                    "Olor",
                    "Viscosidad",
                    "Rpm",
                    "Aguja",
                    "Torque",
                    "Apto para Contenedor",
                    "Observaciones",
                    "Diligenciado Por",
                    "Titular NSOC",
                    "Uso Exclusivo",
                    "Forma Cosmetica",
                    "Check"
            ]
campos_update_cal = [
                "Mesofilos",
                "E Coli",
                "S Aureus",
                "P Aureoginosa",
                "Moho y Levaduras",
                "Observaciones Microbiologia",
                "Cumple Microbiologia",
                "Densidad",
                "Ph",
                "Contenido",
                "Color",
                "Textura",
                "Olor",
                "Viscosidad",
                "Rpm",
                "Aguja",
                "Torque",
                "Apto para Contenedor",
                "Observaciones",
                "Diligenciado Por",
                "Titular NSOC", 
                "Uso Exclusivo",
                "Forma Cosmetica",
            ]
headers_load_prod = [
                "Numero Control",
                "Fecha Solicitud",
                "Numero Cotizacion",
                "PT",
                "Producto",
                "Codigo Caja",
                "Caja Corrugada",
                "¿Cual?",
                "Banda Dimensiones",
                "Banda Temperatura Tunel",
                "Banda Velocidad Tunel",
                "Herramienta Usada para Prueba",
                "Observaciones Funda",
                "Temperatura Sellado Colapsible",
                "Tiempo de Calentamiento",
                "Observaciones Sellado",
                "Hermeticidad",
                "Ubicacion Lote",
                "Etiqueta Manual",
                "Diseno Produccion",
                "Metodo Fabriacion",
                "Diligenciado",
                "Unidades/Caja",
                "Dimensiones Parrilla",
                "Caja Impresa",
                "Leva Parrilla",
                "Rotulo",
                "Rotulo Texto",
                "Clave",
                "Check"
            ]
campos_update_prod = [
                "Codigo Caja",
                "Caja Corrugada",
                "¿Cual?",
                "Banda Dimensiones",
                "Banda Temperatura Tunel",
                "Banda Velocidad Tunel",
                "Herramienta Usada para Prueba",
                "Observaciones Funda",
                "Temperatura Sellado Colapsible",
                "Tiempo de Calentamiento",
                "Observaciones Sellado",
                "Hermeticidad",
                "Ubicacion Lote",
                "Etiqueta Manual",
                "Diseno Produccion",
                "Metodo Fabriacion",
                "Diligenciado",
                "Unidades/Caja",
                "Dimensiones Parrilla",
                "Caja Impresa",
                "Lleva Parrilla",
                "Rotulo",
                "Rotulo Texto",
                "Clave"
            ]
